---
# yamllint disable rule:line-length
default_language_version:
  python: python3.8
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: pretty-format-json
        args:
          - --autofix
      - id: detect-private-key
  - repo: git://github.com/igorshubovych/markdownlint-cli
    rev: v0.26.0
    hooks:
      - id: markdownlint
  - repo: git://github.com/adrienverge/yamllint
    rev: v1.26.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        types: [file, yaml]
        entry: yamllint --strict
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v5.0.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
