- hosts: localhost
  gather_facts: false

- hosts: localhost
  vars:
    ExternalID:  6ba0ea21-eb55-4dc8-a7ec-1ced1269495b
    ResourceNamePrefix:  james-bc-read
  tasks:
     - name: Template expand the assum role policy
       template:
         src: assume.json.j2
         dest: assume.json
     - name: Create bridgecrew readonly role with description and tags
       community.aws.iam_role:
         name: "{{ ResourceNamePrefix }}-bridgecrewcwsrole"
         assume_role_policy_document: "{{ lookup('file','assume.json') }}"
         description: Bridgecrew read only role
         managed_policies:
           - arn:aws:iam::aws:policy/SecurityAudit
           - arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
         tags:
           createdby: bridgecrew
     - name: create inline policy
       community.aws.iam_policy:
         iam_type: role
         iam_name: "{{ ResourceNamePrefix }}-bridgecrewcwsrole"
         policy_document: policy.json
         policy_name: BridgecrewDescribePolicy
         state: present
         # - name: Send notification messages via SNS with short message for SMS
         # community.aws.sns:
         #  msg: '{{ inventory_hostname }} has completed the play.'
         #  sms: deployed!
         # subject: Deploy complete!
         # topic: deploy
         #elegate_to: localhost
