---
api_token: "{{lookup('env', 'BRIDGECREW_TOKEN')}}"  # from your integrations page in the bridgecrew platform
org_name: <yourorg>  # changes per user/org
ResourceNamePrefix: "{{ org_name }}-bc-read"
customer_name: "{{ org_name }}"
resource_name_prefix: "{{ org_name }}-bc"
region: us-west-2  # SNS endpoint has to be in the same region as aws AWS_REGION value
role_name: "{{ ResourceNamePrefix }}-bridgecrewcwssarole"
topic: "handle-customer-actions"
